[colors]
foreground = "#DEDBEB"

ansi = ["#E83F80",
"#ADCFBC",
"#F7D98D",
"#BDCEED",
"#A2BAA8",
"#DEDBEB",
"#E83F80",
"#ADCFBC",
"#F7D98D",
"#BDCEED",
"#9985D1",
"#A2BAA8",
"#DEDBEB",
"#9985D1"
]

brights = ["#2C223C",
"#DEDBEB",
"#84C49B",
"#B4A4DE",
"#23223D",
"#2C223C",
"#DEDBEB"]
