[colors]
foreground = "#cdd6f4"
background = "#1e1e2e"
selection_bg = "#364A82"
selection_fg = "#c0caf5"

ansi = ["#1D202F", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#a9b1d6"]
brights = ["#414868", "#f7768e", "#9ece6a", "#e0af68", "#7aa2f7", "#bb9af7", "#7dcfff", "#c0caf5"]


[metadata]
aliases = []
author = 'Tokyonight'
name = 'tokyonight_storm'
