#!/bin/env bash
itemsFind=$(find *)
selected=$(echo "$itemsFind" | fzf --cycle --prompt="cdtm > " --exit-0)

if [ -n "$selected" ]
then
  cd "$selected" || exit
  
  tmux new-session -s CdTm -n IDE -d
  tmux new-window -t CdTm -d -n zsh
  tmux new-window -t CdTm -d -n Bottom
  
  # tmux send-keys -t CdTm:IDE "ide" Enter
  tmux send-keys -t CdTm:Bottom "btm" Enter
  
  tmux select-window -t CdTm:IDE
  tmux split-window -v -p 20
  tmux send-keys -t CdTm:IDE "clear" Enter
  tmux split-window -h -p 66
  tmux send-keys -t CdTm:IDE "clear" Enter
  tmux split-window -h -p 50
  tmux send-keys -t CdTm:IDE "clear" Enter
  
  tmux -u attach -t CdTm
else
  exit
fi
