#!/bin/env bash
itemsFind=$(find *)
selected=$(echo "$itemsFind" | fzf --cycle --prompt="cdtm > " --exit-0)

if [ -n "$selected" ]
then
  cd "$selected" || exit
  
  tmux split-window -v -p 20
  tmux send-keys "clear" Enter
  tmux split-window -h -p 50
  tmux send-keys "clear" Enter
else
  exit
fi
