#!/bin/sh

cd $1 || return

tmux new-session -s CdTm -n IDE -d
tmux new-window -t CdTm -d -n zsh
tmux new-window -t CdTm -d -n BashTop

# tmux send-keys -t CdTm:IDE "ide" Enter
tmux send-keys -t CdTm:BashTop "bashtop" Enter

tmux select-window -t CdTm:IDE
tmux split-window -v -p 5
tmux send-keys -t CdTm:IDE "clear" Enter
tmux split-window -h -p 66
tmux send-keys -t CdTm:IDE "clear" Enter
tmux split-window -h -p 50
tmux send-keys -t CdTm:IDE "clear" Enter

tmux -u attach -t CdTm

