#!/bin/sh

cd ~/dotfiles/nvim

tmux new-session -s RustTm -n IDE -d
tmux new-window -t RustTm -d -n zsh
tmux new-window -t RustTm -d -n BashTop

# tmux send-keys -t RustTm:IDE "ide" Enter
tmux send-keys -t RustTm:BashTop "bashtop" Enter

tmux select-window -t RustTm:IDE
tmux split-window -v -p 5
tmux send-keys -t RustTm:IDE "clear" Enter
tmux split-window -h -p 66
tmux send-keys -t RustTm:IDE "clear" Enter
tmux split-window -h -p 50
tmux send-keys -t RustTm:IDE "clear" Enter

tmux -u attach -t RustTm

