#!/usr/bin/env bash

cd ~/neovim/ || exit
git pull

export CFLAGS="-fuse-ld=mold"
export CXXFLAGS="-fuse-ld=mold"
export LDFLAGS="-fuse-ld=mold"

sudo make CMAKE_BUILD_TYPE=Release
sudo make install
cd || exit
