#!/bin/bash

# Attach or create tmux session name the same as the current directory
# by Chris Toomey

session_name="$(basename "$PWD" | tr . -)"

session_exits() {
  tmux list-sessions | sed -E 's/:.*$//' | grep -q "^$session_name"
}

not_in_tmux() {
  [[ -z "$TMUX" ]]
}

if not_in_tmux; then
  tmux -u -2 new-session -As "$session_name"
else 
  if ! session_exits; then
    (TMUX='' tmux -u -2 new-session -Ad -s "$session_name")
  fi
  tmux -u switch-client -t "$session_name"
fi
