.TH "dotfiles" 1

.SH "dotfiles"
.PP
Hey this is my dotfiles repository , From which you can download my config files
smile rocket
.PP
#[1] I'm an n00b
.sp
[1] # dotfiles
.nf
.fi


.SH "* My default desktop Environment `\f[CR]hyprland\fP` and `\f[CR]wezterm\fP` with `\f[CR]zsh\fP` and `\f[CR]shellfetch\fP` and combined with `\f[CR]zellij\fP` , The prompt is Starship[2] and the color is catppuccin[3]"
.PP
20221028_14h57m31s_grim[img4]
.sp
[2] https://starship\.rs dotfiles
.nf
.fi
[3] https://github\.com/catppuccin/nvim dotfiles
.nf
.fi


.SH "* One of my Nvim-essential and all time red heart  is telescope.nvim[5] file picker"
.PP
20221028_14h58m58s_grim[img6]
.sp
[5] https://github\.com/nvim\-telescope/telescope\.nvim dotfiles
.nf
.fi


.SH "* The Colorscheme for is catppuccin[7] looks so sick red heart red heart fire"
.PP
20221028_14h59m35s_grim[img8]
.sp
[7] https://github\.com/catppuccin/nvim dotfiles
.nf
.fi


.SH "The Anime Wallpapers are provided by a git repo by"
.PP
\-\- ThePrimeagen[9]
.sp
[9] https://github\.com/ThePrimeagen/anime dotfiles
.nf
.fi


.SH "Changing Neovim in lua-config :smiley:"

.SH "A note for me ..."

.SS "To Setup Rust-analyzer for nvim Then"
.PP
\-\- Follow This Link[10]
.sp
[10] https://sharksforarms\.dev/posts/neovim\-rust/ dotfiles
.nf
.fi


.SS "To Setup Clangd for nvim Then do this"
.PP
\-\- `\f[CR]sudo pacman \-S clangd\fP`
.PP
\-\- `\f[CR]sudo pacman \-S llvm\fP` \-\- " Don't forget to make a project using projectCreate
script else you are not going to have lsp\-server"
.PP
And then you are all good to Go

.SS "The Nvim review is done by ThePrimeagen[11] in this video"
.sp
[11] github\.com/ThePrimeagen dotfiles
.nf
.fi

.SS "The commands to setup nvim-lsp"
.RS
.PP
.nf
sudo npm install \-g vim\-language\-server
sudo npm install \-g pyright
sudo npm install \-g typescript typescript\-language\-server
sudo npm i \-g bash\-language\-server
sudo npm i \-g vscode\-langservers\-extracted
sudo npm install \-g dockerfile\-language\-server\-nodejs
sudo npm install \-g ocaml\-language\-server
sudo npm install \-g vls
sudo yarn global add yaml\-language\-server
.fi
.RE

.SH "to setup lua lsp follow this link[12] , and don't forget to make a directory under ~/.config/nvim named as language-server and do everything under it"
.sp
[12] https://github\.com/sumneko/lua\-language\-server/wiki/Build\-and\-Run\-(Standalone) dotfiles
.nf
.fi

.SH "to setup gopls run"
.RS
.PP
.nf
cd dotfiles/
GO111MODULE=on go get \-u golang\.org/x/tools/gopls@latest
sudo ln \-s /home/arpangreat/go/bin/* /usr/bin
.fi
.RE

.SH "To setup jdtls"
.RS
.Bl
.IP \(bu 4
first delete ~/dotfiles/nvim/jdtl\-language\-server\-latest by
`\f[CR]rm \-rf jdt\-language\-latest\-server\fP`
.El
.Bl
.IP \(bu 4
then , extract ~/dotfiles/nvim/jdt\-language\-server\-latest\.tar\.gz inside
`\f[CR]~/dotfiles/nvim/\fP`
.El
.Bl
.IP \(bu 4
tweak `\f[CR]\.zshrc\fP` respective java file paths if needed
.El
.Bl
.IP \(bu 4
\fBmake project with `\f[CR]projectCreate\fP` script inside ~/dotfiles/custom\-scripts
and lang name should be `\f[CR]gradle\fP` not `\f[CR]java\fP`\fP
.El
.Bl
.IP \(bu 4
And you are all done
.El
.RE

.SH "after doing everything don't forget to run `\f[CR]:TSInstall all\fP` in nvim to install Treesitter"

.SH "to use screenshot.sh run"
.RS
.PP
.nf
sudo pacman \-S grim
[sudo](sudo) pacman \-S slurp
.fi
.RE

.SH "A Life hack for shell , while typing any password show asterisks for every password"
.RS
.PP
.nf
sudo visudo
# Then type in any area
Defaults env_reset,pwfeedback
.fi
.RE

.SH "How to setup tmux for italics from here[13]"
.sp
[13] https://rsapkf\.xyz/blog/enabling\-italics\-vim\-tmux dotfiles
.nf
.fi

.SH "try to make a install script for installing everything"

.SH "IF NVIM BUILD FROM SOURCE BREAKS , use ./nvim/nvim.txt commit tag to fallback to safe zone, also use it inside official neovim repo clone inside $HOME"
.PP
`\f[CR]git checkout #the tag\fP`

.SH "IF TOUCHPAD DOESN'T WORK Then"
.PP
visit[14]
.sp
[14] https://askubuntu\.com/questions/1280240/lenovo\-touchpad\-v15\-iil\-not\-working\-10th\-gen\-intel dotfiles
.nf
.fi


.SH "Fonts ( Also see Fonts/ )"
.PP
Download from
Operator Mono[15]
Download from
Operator Book[16]
Download from
Operator Itaic[17]
Download from
Operator Bold[18]
.sp
[15] https://fontsfree\.net/operator\-mono\-medium\-font\-download\.html dotfiles
.nf
.fi
[16] https://fontsfree\.net/operator\-mono\-book\-font\-download\.html dotfiles
.nf
.fi
[17] https://fontsfree\.net/operator\-mono\-book\-italic\-2\-font\-download\.html dotfiles
.nf
.fi
[18] https://fontsfree\.net/operator\-mono\-bold\-font\-download\.html dotfiles
.nf
.fi


.SS "And follow this link to use ligatures Support[19]"
.sp
[19] https://github\.com/kiliman/operator\-mono\-lig dotfiles
.nf
.fi
.sp
[img4] https://user\-images\.githubusercontent\.com/46556080/198555517\-9379d760\-55cd\-4b63\-b37f\-72f1b94768ec\.png dotfiles
.nf
.fi
[img6] https://user\-images\.githubusercontent\.com/46556080/198556784\-e9651ac7\-9def\-4cd2\-9f42\-c6e4c0e69a38\.png dotfiles
.nf
.fi
[img8] https://user\-images\.githubusercontent\.com/46556080/198557034\-9c1da1df\-da25\-4bf7\-b0b3\-1a80f1a6b38a\.png dotfiles
.nf
.fi
