# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 50000
scan_timeout = 50000

palette = "catppuccin_mocha"

[character]
success_symbol = "[󰘧](bold green)"
error_symbol = "[󰘧](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_visual_symbol = "[V](bold yellow)"
vimcmd_replace_one_symbol = "[r](bold purple)"
vimcmd_replace_symbol = "[R](bold purple)"

[directory]
style = "blue bold"
read_only = " "

[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true
symbol = "  "

[docker_context]
disabled = true
symbol = " "

[git_branch]
disabled = true
symbol = " "

[git_status]
disabled = true

[git_commit]
disabled = true

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
