theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = true
bufferline = "always"
cursorline = true
completion-trigger-len = 0
auto-save = true
true-color = true
color-modes = true
scrolloff = 15
soft-wrap.enable = true
undercurl = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator", "workspace-diagnostics"]
right = [
  "diagnostics",
  "total-line-numbers",
  "position",
  "separator",
  "position-percentage",
  "separator",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
"space" = { w = ":w", q = ":q", e = { x = ":q!" } }
g = { a = "code_action" }
"esc" = ["collapse_selection"]

[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"
