theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.lsp]
display-messages = true

[keys.normal]
"space" = { w = ":w", q = ":q", e = { x = ":q!"}}
g = { a = "code_action" }
