[[language]]
name = "rust"
scope = "source.rust"
formatter = { command = "rustfmt" }
auto-format = true

[language-server.rust-analyzer.config]
check = { command = "clippy", features = "all" }
diagnostics = { experimental = { enable = true } }
hover = { actions = { enable = true } }
typing = { autoClosingAngleBrackets = { enable = true } }

[language-server.rust-analyzer.config.inlayHints]
closureCaptureHints = { enable = true }
closureReturnTypeHints = "always"
expressionAdjustmentHints = "always"

[[language]]
name = "python"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true

[language-server.clangd]
command = "clangd"
args = [
		"--background-index",
		"--pch-storage=memory",
		"--clang-tidy",
		"--suggest-missing-includes",
		"--cross-file-rename",
		"--completion-style=detailed",
		"--offset-encoding=utf-16",
]

[[language]]
name = "cmake"
auto-format = true

[[language]]
name = "zig"
scope = "source.zig"
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "v"
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }

[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md"] }
auto-format = true

[language-server.deno-lsp] 
command = 'deno'
args = ['lsp']
config = { enable = true, unstable = true }

[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts"] }
auto-format = true
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-id = "typescript"
language-servers = ["deno-lsp"]


[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js"]}
auto-format = true
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-id = "javascript"
language-servers = ["deno-lsp"]

[[language]]
name = "jsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx"] }
auto-format = true
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-id = "javascriptreact"
language-servers = ["deno-lsp"]

[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx"] }
auto-format = true
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-id = "typescriptreact"
language-servers = ["deno-lsp"]

[[language]]
name = "go"
auto-format = true
language-servers = ["taplo"]

[language-server.taplo]
command = ""
