[[language]]
name = "rust"
scope = "source.rust"
# file-types = [ "rust" ]
language-server = { command = "rust-analyzer" }
formatter = { command = "rustfmt" }
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "python"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "zig"
scope = "source.zig"
language-server = { command = "zls" }
auto-format = true

[[language]]
name = "typescript"
scope = "source.ts"
language-server = { command = "typescript-language-server --stdio" }
auto-format = true

[[language]]
name = "tsx"
scope = "source.tsx"
auto-format = true

[[language]]
name = "toml"
scope = "source.toml"
auto-format = true
