[[language]]
name = "rust"
scope = "source.rust"
# file-types = [ "rust" ]
language-server = { command = "rust-analyzer" }
formatter = { command = "rustfmt" }
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "python"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "zig"
scope = "source.zig"
language-server = { command = "zls" }
auto-format = true

[[language]]
name = "typescript"
scope = "source.ts"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts"] }
auto-format = true

[[language]]
name = "tsx"
scope = "source.tsx"
auto-format = true
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts"] }

[[language]]
name = "toml"
scope = "source.toml"
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true
