[[language]]
name = "rust"
scope = "source.rust"
language-server = { command = "rust-analyzer" }
formatter = { command = "rustfmt" }
auto-format = true

[language.config]
check = { command = "clippy", features = "all" }
diagnostics = { experimental = { enable = true } }
hover = { actions = { enable = true } }
typing = { autoClosingAngleBrackets = { enable = true } }

[language.config.inlayHints]
closureCaptureHints = { enable = true }
closureReturnTypeHints = "always"
expressionAdjustmentHints = "always"

[[language]]
name = "python"
auto-format = true

[[language]]
name = "cpp"
auto-format = true
language-server = { command = "clangd", args = [
  "--compile-commands-dir=compile_commands_dir",
] }

[[language]]
name = "c"
auto-format = true

[[language]]
name = "cmake"
auto-format = true

[[language]]
name = "zig"
scope = "source.zig"
language-server = { command = "zls" }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "v"
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js"] }
config = { enable = true, lint = true, unstable = true }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }

[[language]]
name = "markdown"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx"] }
auto-format = true

[[language]]
name = "toml"
language-server = { command = ""}
