[[language]]
name = "rust"
scope = "source.rust"
# file-types = [ "rust" ]
language-server = { command = "rust-analyzer" }
formatter = { command = "rustfmt" }
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "python"
auto-format = true

[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "c"
auto-format = true

[[language]]
name = "zig"
auto-format = true
