[ui.window.box]
idth = 664
min_width = 664
max_width = 664
height = 396
min_height = 396
max_height = 396

# List constraints are critical - without these, the window shrinks when empty
[ui.window.box.scroll.list]
height = 300
min_height = 300
max_height = 300

[ui.window.box.scroll.list.item.icon]
pixel_size = 40
