#!/bin/bash

status=$(acpi -b | head -n1 | awk '{print $3}' | sed 's/,//')
perc=$(acpi -b | head -n1 | awk '{print $4}' | sed 's/[^0-9]*//g')

if [[ "$1" == "rofi" ]]; then
    echo "$status $perc%"
    acpi | cut -d',' -f3 | xargs
    exit
fi

if [[ "$BLOCK_BUTTON" == "1" ]]; then
    . "$(dirname $0)/rofi.sh"
    rofi_menu "Battery" 30
fi

if [[ "$status" == "Charging" ]] || [[ "$status" == "Full" ]] ; then
    out+=$(printf "\uf1e6 ")
fi

if [[ "$perc" -le "15" ]]; then
    out+=$(printf "\uf244\n")
elif [[ "$perc" -le "37" ]]; then
    out+=$(printf "\uf243\n")
elif [[ "$perc" -le "62" ]]; then
    out+=$(printf "\uf242\n")
elif [[ "$perc" -le "84" ]]; then
    out+=$(printf "\uf241\n")
else
    out+=$(printf "\uf240\n")
fi

if [[ "$status" == "Full" ]]; then
    echo "$out"
    echo "$out"
    echo "#00FF00"
elif [[ "$perc" -le "15" ]] && [[ "$status" != "Charging" ]]; then
    if [[ "$(bbc property $BLOCK_ID execdata | tail -n1)" != "#FF0000" ]]; then
        notify-send -u critical -i battery -t 60000 "Battery low" "$perc%"
    fi

    echo "$out"
    echo "$out"
    echo "#FF0000"
else
    echo "$out"
fi
