#!/bin/bash

if [[ "$1" == "rofi" ]]; then
    P1="Shutdown"
    C1="systemctl poweroff"
    P2="Hybrid"
    C2="systemctl hybrid-sleep"
    P3="Hibernate"
    C3="systemctl hibernate"
    P4="Suspend"
    C4="systemctl suspend"
    P5="Restart"
    C5="systemctl reboot"
    P6="Logout"
    C6="bspc quit"

      if [[ "$2" == "$P1" ]]; then eval $C1 &>/dev/null &
    elif [[ "$2" == "$P2" ]]; then eval $C2 &>/dev/null &
    elif [[ "$2" == "$P3" ]]; then eval $C3 &>/dev/null &
    elif [[ "$2" == "$P4" ]]; then eval $C4 &>/dev/null &
    elif [[ "$2" == "$P5" ]]; then eval $C5 &>/dev/null &
    elif [[ "$2" == "$P6" ]]; then eval $C6 &>/dev/null &
    else
        echo $P1
        echo $P2
        echo $P3
        echo $P4
        echo $P5
        echo $P6
    fi

    exit
fi

if [[ "$BLOCK_BUTTON" == "1" ]]; then
    . "$(dirname $0)/rofi.sh"
    rofi_menu "Power" 13 6
fi

printf "\uf011\n"
