#!/bin/bash

DATADIR="$(eval echo ~/.config/blockbar/scripts/data)"

if [[ ! -d "$DATADIR" ]]; then
    mkdir "$DATADIR"
fi

if [[ "$BLOCK_BUTTON" != "1" && "$BLOCK_BUTTON" != "3" ]]; then
    bbc property $BLOCK_ID execdata $(printf "\uf110")
    bbc setting constwidth:reset $BLOCK_ID
    (checkupdates; yay -Pu) | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g" | cut -d' ' -f1 | sort -u > "$DATADIR/updates"
fi

LIST=$(cat "$DATADIR/updates")
NUM=$(echo "$LIST" | grep -c .)

if [[ "$1" == "rofi" ]]; then
    echo "$LIST"
    exit
fi

if [ "$BLOCK_BUTTON" == "1" ]; then
    alacritty --class update -e bash -c "yay && sudo -E pacdiff; echo Done - Press enter to exit; read" >/dev/null
    BLOCK_BUTTON= $0
    exit
elif [ "$BLOCK_BUTTON" == "3" ]; then
    . "$(dirname $0)/rofi.sh"
    NOCLICK=1 rofi_menu "Updates" 25 $(( NUM<30?NUM:25 ))
fi

if [[ "$NUM" > "0" ]]; then
    printf "\uf381 %d\n%d\n" "$NUM" "$NUM"
fi
