[[entries]]
default = true
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"

[[entries]]
name = "Ecosia"
url = "https://www.ecosia.org/search?q=%TERM%"

[[entries]]
name = "Yandex"
url = "https://yandex.com/search/?text=%TERM%"
