complete -c btm -n "__fish_use_subcommand" -s C -l config -d 'Sets the location of the config file.'
complete -c btm -n "__fish_use_subcommand" -l color -d 'Use a color scheme, use --help for supported values.' -r -f -a "default default-light gruvbox gruvbox-light nord nord-light"
complete -c btm -n "__fish_use_subcommand" -s t -l default_time_value -d 'Default time value for graphs in ms.'
complete -c btm -n "__fish_use_subcommand" -l default_widget_count -d 'Sets the n\'th selected widget type as the default.'
complete -c btm -n "__fish_use_subcommand" -l default_widget_type -d 'Sets the default widget type, use --help for more info.'
complete -c btm -n "__fish_use_subcommand" -s r -l rate -d 'Sets a refresh rate in ms.'
complete -c btm -n "__fish_use_subcommand" -s d -l time_delta -d 'The amount in ms changed upon zooming.'
complete -c btm -n "__fish_use_subcommand" -s k -l kelvin -d 'Sets the temperature type to Kelvin.'
complete -c btm -n "__fish_use_subcommand" -s f -l fahrenheit -d 'Sets the temperature type to Fahrenheit.'
complete -c btm -n "__fish_use_subcommand" -s c -l celsius -d 'Sets the temperature type to Celsius.'
complete -c btm -n "__fish_use_subcommand" -l autohide_time -d 'Temporarily shows the time scale in graphs.'
complete -c btm -n "__fish_use_subcommand" -s b -l basic -d 'Hides graphs and uses a more basic look.'
complete -c btm -n "__fish_use_subcommand" -l battery -d 'Shows the battery widget.'
complete -c btm -n "__fish_use_subcommand" -s S -l case_sensitive -d 'Enables case sensitivity by default.'
complete -c btm -n "__fish_use_subcommand" -l process_command -d 'Show processes as their commands by default.'
complete -c btm -n "__fish_use_subcommand" -l mem_as_value -d 'Defaults to showing process memory usage by value.'
complete -c btm -n "__fish_use_subcommand" -l disable_click -d 'Disables mouse clicks.'
complete -c btm -n "__fish_use_subcommand" -s m -l dot_marker -d 'Uses a dot marker for graphs.'
complete -c btm -n "__fish_use_subcommand" -s g -l group -d 'Groups processes with the same name by default.'
complete -c btm -n "__fish_use_subcommand" -s a -l hide_avg_cpu -d 'Hides the average CPU usage.'
complete -c btm -n "__fish_use_subcommand" -l hide_table_gap -d 'Hides the spacing between table headers and entries.'
complete -c btm -n "__fish_use_subcommand" -l hide_time -d 'Completely hides the time scaling.'
complete -c btm -n "__fish_use_subcommand" -l show_table_scroll_position -d 'Shows the scroll position tracker in table widgets.'
complete -c btm -n "__fish_use_subcommand" -s l -l left_legend -d 'Puts the CPU chart legend to the left side.'
complete -c btm -n "__fish_use_subcommand" -l disable_advanced_kill -d 'Hides advanced options to stop a process on Unix-like systems.'
complete -c btm -n "__fish_use_subcommand" -s R -l regex -d 'Enables regex by default.'
complete -c btm -n "__fish_use_subcommand" -s T -l tree -d 'Defaults to showing the process widget in tree mode.'
complete -c btm -n "__fish_use_subcommand" -l network_use_bytes -d 'Displays the network widget using bytes.'
complete -c btm -n "__fish_use_subcommand" -l network_use_log -d 'Displays the network widget with a log scale.'
complete -c btm -n "__fish_use_subcommand" -l network_use_binary_prefix -d 'Displays the network widget with binary prefixes.'
complete -c btm -n "__fish_use_subcommand" -s u -l current_usage -d 'Sets process CPU% to be based on current CPU%.'
complete -c btm -n "__fish_use_subcommand" -l use_old_network_legend -d 'DEPRECATED - uses the older network legend.'
complete -c btm -n "__fish_use_subcommand" -s W -l whole_word -d 'Enables whole-word matching by default.'
complete -c btm -n "__fish_use_subcommand" -s h -l help -d 'Prints help information.  Use --help for more info.'
complete -c btm -n "__fish_use_subcommand" -s V -l version -d 'Prints version information.'
