return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufReadPost" },
	-- lazy = false,
	branch = "main",
	dependencies = {
		-- "JoosepAlviste/nvim-ts-context-commentstring",
		-- "OXY2DEV/markview.nvim",
	},
	-- opts = {},
	config = function()
		vim.api.nvim_create_autocmd("FileType", {
			pattern = {
				"rust",
				"zig",
				"javascript",
				"cpp",
				"c",
				"typescript",
				"go",
				"gomod",
				"gleam",
				"json",
				"jsonc",
				"java",
				"toml",
				"html",
				"css",
				"ruby",
				"ocaml",
				"php",
				"comment",
				"java",
				"python",
				"dart",
				"fish",
				"tmux",
				"sql",
				"blade",
				"typescriptreact",
				"vim",
				"lua",
				"luadoc",
				"ocaml",
				"ocamllex",
				"ocaml_interface",
				"vimdoc",
				"angular",
				"vue",
				"hyprlang",
				"diff",
				"markdown",
				"markdown_inline",
				"yaml",
				"bash",
			},
			callback = function()
				vim.treesitter.start()
				vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"
				vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
			end,
		})
	end,
}
