-- vim.api.nvim_command("colorscheme tokyonight-storm")
-- vim.api.nvim_command("colorscheme horizon")
vim.api.nvim_command("colorscheme catppuccin")
-- vim.cmd("colorscheme solarized-osaka")
-- vim.cmd("colorscheme bamboo")
